export type Job =
  | 'Frontend'
  | 'Backend'
  | 'Fullstack'
  | 'Project Management'
  | 'DevOps'
  | 'Cloud Development'
  | 'Team Management'
  | 'Software Architecture'
  | 'Team Building'
  | 'Budget Management'
  | 'Stackholders Management'
  | 'Clients Management'
  | 'Leadership'
  | 'Stakeholders Management'
  | 'Team Building'
  | 'Architecture Design';
